/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IcMenuToggle {
        "active": boolean;
        "label": string;
    }
    interface IcSwitch {
        "active": boolean;
        "label": string;
    }
}
declare global {
    interface HTMLIcMenuToggleElement extends Components.IcMenuToggle, HTMLStencilElement {
    }
    var HTMLIcMenuToggleElement: {
        prototype: HTMLIcMenuToggleElement;
        new (): HTMLIcMenuToggleElement;
    };
    interface HTMLIcSwitchElement extends Components.IcSwitch, HTMLStencilElement {
    }
    var HTMLIcSwitchElement: {
        prototype: HTMLIcSwitchElement;
        new (): HTMLIcSwitchElement;
    };
    interface HTMLElementTagNameMap {
        "ic-menu-toggle": HTMLIcMenuToggleElement;
        "ic-switch": HTMLIcSwitchElement;
    }
}
declare namespace LocalJSX {
    interface IcMenuToggle {
        "active"?: boolean;
        "label"?: string;
    }
    interface IcSwitch {
        "active"?: boolean;
        "label"?: string;
    }
    interface IntrinsicElements {
        "ic-menu-toggle": IcMenuToggle;
        "ic-switch": IcSwitch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ic-menu-toggle": LocalJSX.IcMenuToggle & JSXBase.HTMLAttributes<HTMLIcMenuToggleElement>;
            "ic-switch": LocalJSX.IcSwitch & JSXBase.HTMLAttributes<HTMLIcSwitchElement>;
        }
    }
}
