/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IcMenuToggle {
        "active": boolean;
        "label": string;
    }
    interface IcSocialNetwork {
        "image": string;
        "name": string;
        "target": string;
        "url": string;
        "urlTitle": string;
    }
    interface IcSwitch {
        "active": boolean;
        "label": string;
    }
}
declare global {
    interface HTMLIcMenuToggleElement extends Components.IcMenuToggle, HTMLStencilElement {
    }
    var HTMLIcMenuToggleElement: {
        prototype: HTMLIcMenuToggleElement;
        new (): HTMLIcMenuToggleElement;
    };
    interface HTMLIcSocialNetworkElement extends Components.IcSocialNetwork, HTMLStencilElement {
    }
    var HTMLIcSocialNetworkElement: {
        prototype: HTMLIcSocialNetworkElement;
        new (): HTMLIcSocialNetworkElement;
    };
    interface HTMLIcSwitchElement extends Components.IcSwitch, HTMLStencilElement {
    }
    var HTMLIcSwitchElement: {
        prototype: HTMLIcSwitchElement;
        new (): HTMLIcSwitchElement;
    };
    interface HTMLElementTagNameMap {
        "ic-menu-toggle": HTMLIcMenuToggleElement;
        "ic-social-network": HTMLIcSocialNetworkElement;
        "ic-switch": HTMLIcSwitchElement;
    }
}
declare namespace LocalJSX {
    interface IcMenuToggle {
        "active"?: boolean;
        "label"?: string;
    }
    interface IcSocialNetwork {
        "image"?: string;
        "name"?: string;
        "target"?: string;
        "url"?: string;
        "urlTitle"?: string;
    }
    interface IcSwitch {
        "active"?: boolean;
        "label"?: string;
    }
    interface IntrinsicElements {
        "ic-menu-toggle": IcMenuToggle;
        "ic-social-network": IcSocialNetwork;
        "ic-switch": IcSwitch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ic-menu-toggle": LocalJSX.IcMenuToggle & JSXBase.HTMLAttributes<HTMLIcMenuToggleElement>;
            "ic-social-network": LocalJSX.IcSocialNetwork & JSXBase.HTMLAttributes<HTMLIcSocialNetworkElement>;
            "ic-switch": LocalJSX.IcSwitch & JSXBase.HTMLAttributes<HTMLIcSwitchElement>;
        }
    }
}
